server:
  port: 10098
spring:
  application:
    name: ktv-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10099/eureka
zuul:
  prefix: /api
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000
