server:
  port: 10097
spring:
  application:
    name: ktv-auth
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10099/eureka
swagger:
  base-package: com.ktv.web.controller
